# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Netresearch DTT GmbH

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netresearch\NrWellknown\:
    resource: '../Classes/*'
